# Generated by Django 2.0.3 on 2018-03-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('review', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('avatar', models.CharField(default='/s/image/avatar.png', max_length=256)),
                ('nick', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('forbid', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('uid', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comments', to='backend.Guest'),
        ),
        migrations.AddField(
            model_name='comment',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='art_comments', to='backend.BlogsPost'),
        ),
    ]
